In [6]:
#Deep Learning Week 3 Programs 
#5. Write a python naive implementation for element wise addition of two tensors. 

import numpy as np 
def naïve_add(x,y):      
    assert len(x.shape)==2      
    assert x.shape==y.shape      
    for i in range(x.shape[0]):          
        for j in range(x.shape[1]):             
            x[i,j]+=y[i,j]     
        return x 
x=np.array([[1,2],[3,4]]) 
y=np.array([[3,4],[5,6]]) 
z=naïve_add(x,y)  
print(z) 

[[4 6]
 [3 4]]


In [5]:
#6. Write a Python program for element wise product. 


import numpy as np 
def naive_vector_dot(x,y):   
    assert len(x.shape)==1  
    assert len(y.shape)==1      
    assert x.shape[0]==y.shape[0]     
    z=0
    for i in range(x.shape[0]):         
        z+=x[i]*y[i]
    
    return z
x= np.array([1,2,3,4]) 
y= np.array([10,20,30,40])  
result= naive_vector_dot( x , y)  
print(result)

300


In [7]:
#7. Write a Python program for element wise concatenation.

'''Concatenate tensors in axis running vertically downwards across rows is axis 0.'''

import numpy as np 
x=np.array([[1,2,3,4],[5,6,7,8]]) 
y=np.array([[0,5,6,3],[1,4,2,9]]) 
np.concatenate([x,y],axis=0)



array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [0, 5, 6, 3],
       [1, 4, 2, 9]])

In [8]:
'''Concatenate tensors in axis running horizontally across columns is axis 1.'''
import numpy as np 
x=np.array([[1,2,3,4],[5,6,7,8]]) 
y=np.array([[0,5,6,3],[1,4,2,9]]) 
np.concatenate([x,y],axis=1)

array([[1, 2, 3, 4, 0, 5, 6, 3],
       [5, 6, 7, 8, 1, 4, 2, 9]])

In [11]:
#8.Write a python naive implementation for element wise relu operation 

import numpy as np  
def relu_imp(x):     
    assert len (x.shape)==2      
    for i in range(x.shape[0]):         
        for j in range(x.shape[1]):             
            x[i,j]=max(x[i,j],0)      
    return x  
                
x=np.array([[1,2],[3,4]]) 
relu_imp(x) 

array([[1, 2],
       [3, 4]])